[target.thumbv6m-none-eabi]
runner = "./script/flash.sh"
rustflags = [
  "-C", "linker=flip-link",
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x",
  "-C", "no-vectorize-loops",
]

[build]
target = "thumbv6m-none-eabi"
